apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: is-my-burguer-api
  name: is-my-burguer-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: is-my-burguer-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: is-my-burguer-api
    spec:
      containers:
        - name: is-my-burguer-api
          resources:
            limits:
              cpu: "1"
              memory: "300Mi"
            requests:
              cpu: "300m"
              memory: "300Mi"
          env:
            - name: POSTGRES_PASSWORD
              value: ismyburguer
            - name: POSTGRES_USER
              value: ismyburguer
            - name: MONGO_PASSWORD
              value: ismyburguer
            - name: MONGO_USERNAME
              value: ismyburguer
          image: docker.io/ismaelgcosta/is-my-burguer-app:is-my-burguer-api-1.0.3
          ports:
            - containerPort: 8080
      restartPolicy: Always
status: {}